# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  ugan:

services:

  orderer.ugachain.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.ugachain.com
    container_name: orderer.ugachain.com
    networks:
      - ugan

  peer0.polytech.ugachain.com:
    container_name: peer0.polytech.ugachain.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.polytech.ugachain.com
    networks:
      - ugan

  peer1.polytech.ugachain.com:
    container_name: peer1.polytech.ugachain.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.polytech.ugachain.com
    networks:
      - ugan

  peer0.iae.ugachain.com:
    container_name: peer0.iae.ugachain.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.iae.ugachain.com
    networks:
      - ugan

  peer1.iae.ugachain.com:
    container_name: peer1.iae.ugachain.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.iae.ugachain.com
    networks:
      - ugan

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.polytech.ugachain.com:7051
      - CORE_PEER_LOCALMSPID=PolytechMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/polytech.ugachain.com/peers/peer0.polytech.ugachain.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/polytech.ugachain.com/peers/peer0.polytech.ugachain.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/polytech.ugachain.com/peers/peer0.polytech.ugachain.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/polytech.ugachain.com/users/Admin@polytech.ugachain.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash -c './scripts/script.sh ${CHANNEL_NAME} ${DELAY}; sleep $TIMEOUT'
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/hyperledger/fabric/ugachains/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.ugachain.com
      - peer0.polytech.ugachain.com
      - peer1.polytech.ugachain.com
      - peer0.iae.ugachain.com
      - peer1.iae.ugachain.com
    networks:
      - ugan

