# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  byfn:
services:
  ca0:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-polytech
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.polytech.ugachain.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.polytech.ugachain.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/polytech.ugachain.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerPolytech
    networks:
      - byfn

  ca1:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-iae
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.iae.ugachain.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.iae.ugachain.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/iae.ugachain.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerIAE
    networks:
      - byfn

  orderer.ugachain.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.ugachain.com
    container_name: orderer.ugachain.com
    networks:
      - byfn

  peer0.polytech.ugachain.com:
    container_name: peer0.polytech.ugachain.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.polytech.ugachain.com
    networks:
      - byfn

  peer1.polytech.ugachain.com:
    container_name: peer1.polytech.ugachain.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.polytech.ugachain.com
    networks:
      - byfn

  peer0.iae.ugachain.com:
    container_name: peer0.iae.ugachain.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.iae.ugachain.com
    networks:
      - byfn

  peer1.iae.ugachain.com:
    container_name: peer1.iae.ugachain.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.iae.ugachain.com
    networks:
      - byfn
